name: Docker
on:
  push:
    branches:
    - master
  release:
    types:
    - published
  pull_request:
    branches:
    - master
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/xperimental/flowercare-exporter
        tags: |
          type=semver,pattern={{version}}
          type=ref,event=branch
          type=ref,event=pr
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
