name: Pull-request
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Build and Test
      run: make
